version: '3'
services:

  blablacar.front:
    build: ./react
    env_file:
      - .env
    ports:
      - '80:3000'
    volumes:
      - './react/src:/app/src'
    networks:
      - blablacar

networks:
  blablacar:
    driver: bridge